apiVersion: v1
kind: Service
metadata:
  name: app-host
  namespace: bifrost
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bifrost-app-host
  ports:
    - name: http
      port: 8100
      targetPort: 8100
