"""Bifrost contract models organized by domain."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from src.models._exports import CONTRACT_ALL, CONTRACT_EXPORTS

if TYPE_CHECKING:
    from src.models.contracts.base import (  # noqa: F401
        DataProviderInputMode,
        IntegrationType,
        RetryPolicy,
        generate_entity_id,
    )
    from src.models.contracts.ai_models import (  # noqa: F401
        AIConnectionTestResponse,
        AIModelAssignmentKey,
        AIModelAssignmentResponse,
        AIModelAssignmentUpdate,
        AIModelProfileCreate,
        AIModelProfileMergeRequest,
        AIModelProfileMergeResponse,
        AIModelProfileResponse,
        AIModelProfileUpdate,
        AIModelsResponse,
        AIProviderConnectionCreate,
        AIProviderConnectionResponse,
        AIProviderConnectionSummary,
        AIProviderConnectionUpdate,
        AIProviderKind,
    )
    from src.models.contracts.organizations import (  # noqa: F401
        CreateOrganizationRequest,
        OrganizationBase,
        OrganizationCreate,
        OrganizationPublic,
        OrganizationUpdate,
        UpdateOrganizationRequest,
    )
    from src.models.contracts.users import (  # noqa: F401
        AssignAppsToRoleRequest,
        AssignFormsToRoleRequest,
        AssignKnowledgeToRoleRequest,
        AssignUsersToRoleRequest,
        AssignWorkflowsToRoleRequest,
        CreateRoleRequest,
        CreateUserRequest,
        GrantPermissionsRequest,
        KnowledgeAssignmentInput,
        PermissionsData,
        RoleAppsResponse,
        RoleBase,
        RoleConsumerCounts,
        RoleCreate,
        RoleFormsResponse,
        RoleKnowledgeEntry,
        RoleKnowledgeResponse,
        RolePublic,
        RoleUpdate,
        RoleUserSummary,
        RoleUsersResponse,
        RoleWorkflowsResponse,
        UnassignAgentsFromRoleRequest,
        UnassignAppsFromRoleRequest,
        UnassignFormsFromRoleRequest,
        UnassignKnowledgeFromRoleRequest,
        UnassignUsersFromRoleRequest,
        UnassignWorkflowsFromRoleRequest,
        UpdateRoleRequest,
        BulkUserFailure,
        BulkUserOperation,
        BulkUserResponse,
        UpdateUserRequest,
        UserBase,
        UserCreate,
        UserFormsResponse,
        UserPermission,
        UserPublic,
        UserResponse,
        UserRolesResponse,
        UserUpdate,
    )
    from src.models.contracts.auth import (  # noqa: F401
        AuthStatusResponse,
        DeviceAuthorizeRequest,
        DeviceCodeResponse,
        DeviceTokenErrorResponse,
        DeviceTokenRequest,
        DeviceTokenResponse,
        LoginResponse,
        MFAEnrollVerifyRequest,
        MFAEnrollVerifyResponse,
        MFARequiredResponse,
        MFASetupRequiredResponse,
        MFASetupResponse,
        MFASetupTokenRequest,
        MFAVerifyRequest,
        OAuthLoginRequest,
        OAuthProviderInfo,
        TokenRefresh,
    )
    from src.models.contracts.passkeys import (  # noqa: F401
        PasskeyAuthOptionsRequest,
        PasskeyAuthOptionsResponse,
        PasskeyAuthVerifyRequest,
        PasskeyDeleteResponse,
        PasskeyListResponse,
        PasskeyPublic,
        PasskeyRegistrationOptionsRequest,
        PasskeyRegistrationOptionsResponse,
        PasskeyRegistrationVerifyRequest,
        PasskeyRegistrationVerifyResponse,
    )
    from src.models.contracts.forms import (  # noqa: F401
        CreateFormRequest,
        DataProviderInputConfig,
        FormCaptchaChallenge,
        FormCreate,
        FormConfirmationResponse,
        FormExecutionResponse,
        FormFieldOptionsRequest,
        FormFieldOptionsResponse,
        FormFieldValidation,
        FormPublicationPublic,
        FormPublicationReview,
        FormPublicationUpdate,
        FormPublic,
        FormRuntimeDefinition,
        FormSchema,
        FormSubmissionRequest,
        FormSubmissionResponse,
        FormStartupResponse,
        FormUpdate,
        UpdateFormRequest,
    )
    from src.models.contracts.applications import (  # noqa: F401
        AppFileCreate,
        AppFileListResponse,
        AppFileResponse,
        AppFileUpdate,
        ApplicationCreate,
        ApplicationDefinition,
        ApplicationDraftSave,
        ApplicationListResponse,
        ApplicationPublic,
        ApplicationPublishRequest,
        ApplicationRollbackRequest,
        ApplicationUpdate,
        VersionHistoryEntry,
        VersionHistoryResponse,
    )
    from src.models.contracts.platform_jobs import (  # noqa: F401
        PlatformJobAccepted,
        PlatformJobCancelResponse,
        PlatformJobError,
        PlatformJobListResponse,
        PlatformJobProgress,
        PlatformJobPublic,
        PlatformJobStatus,
    )
    from src.models.contracts.scheduler_diagnostics import (  # noqa: F401
        SchedulerCapacityStatus,
        SchedulerDiagnosticsResponse,
        SchedulerLeaderStatus,
        SchedulerReplicaStatus,
        SchedulerTaskRunStatus,
        SchedulerTaskStatus,
        SystemDiagnosticLogPublic,
    )
    from src.models.contracts.agents import (  # noqa: F401
        AgentCreate,
        AgentPublic,
        AgentSummary,
        AgentUpdate,
        AssignAgentsToRoleRequest,
        ChatRequest,
        ChatResponse,
        ChatStreamChunk,
        ConversationCreate,
        ConversationPublic,
        ConversationSummary,
        MessagePublic,
        RoleAgentsResponse,
        ToolCall,
        ToolResult,
    )
    from src.models.contracts.audit import (  # noqa: F401
        AuditLogActor,
        AuditLogEntry,
        AuditLogListResponse,
    )
    from src.models.contracts.executions import (  # noqa: F401
        AIUsagePublicSimple,
        AIUsageTotalsSimple,
        CleanupTriggeredResponse,
        ExecutionBase,
        ExecutionCreate,
        ExecutionLogPublic,
        ExecutionPublic,
        ExecutionUpdate,
        ExecutionsListResponse,
        StuckExecutionsResponse,
        WorkflowExecution,
        WorkflowExecutionRequest,
        WorkflowExecutionResponse,
    )
    from src.models.contracts.config import (  # noqa: F401
        ConfigBase,
        ConfigCreate,
        ConfigPublic,
        ConfigResponse,
        ConfigUpdate,
        IntegrationConfig,
        SecretBase,
        SecretCreate,
        SecretCreateRequest,
        SecretListResponse,
        SecretPublic,
        SecretResponse,
        SecretUpdate,
        SecretUpdateRequest,
        SetConfigRequest,
        SetIntegrationConfigRequest,
        UpdateConfigRequest,
    )
    from src.models.contracts.oauth import (  # noqa: F401
        CreateOAuthConnectionRequest,
        EntityIdPickerCandidate,
        OAuthCallbackRequest,
        OAuthCallbackResponse,
        OAuthConnection,
        OAuthConnectionDetail,
        OAuthConnectionSummary,
        OAuthCredentials,
        OAuthCredentialsModel,
        OAuthCredentialsResponse,
        OAuthFlowType,
        OAuthProviderBase,
        OAuthProviderCreate,
        OAuthProviderPublic,
        OAuthProviderUpdate,
        OAuthStatus,
        UpdateOAuthConnectionRequest,
    )
    from src.models.contracts.workflows import (  # noqa: F401
        AssignRolesToWorkflowRequest,
        DataProviderMetadata,
        FormDiscoveryMetadata,
        MetadataResponse,
        RegisterWorkflowRequest,
        RegisterWorkflowResponse,
        ValidationIssue,
        WorkflowKey,
        WorkflowKeyCreateRequest,
        WorkflowKeyResponse,
        WorkflowMetadata,
        WorkflowParameter,
        WorkflowRolesResponse,
        WorkflowUpdateRequest,
        WorkflowValidationRequest,
        WorkflowValidationResponse,
        EntityUsage,
        WorkflowUsageStats,
        DeleteWorkflowRequest,
    )
    from src.models.contracts.data_providers import (  # noqa: F401
        DataProviderOption,
        DataProviderRequest,
        DataProviderResponse,
    )
    from src.models.contracts.dashboard import (  # noqa: F401
        DailyMetricsEntry,
        DailyMetricsResponse,
        DashboardMetricsResponse,
        ExecutionTimeSeriesBucket,
        ExecutionTimeSeriesResponse,
        ROISnapshot,
        ExecutionStats,
        OrganizationMetricsResponse,
        OrganizationMetricsSummary,
        PlatformMetricsResponse,
        RecentFailure,
        ResourceMetricsEntry,
        ResourceMetricsResponse,
        WorkflowMetricsResponse,
        WorkflowMetricsSummary,
    )
    from src.models.contracts.health import (  # noqa: F401
        BasicHealthResponse,
        GeneralHealthResponse,
        HealthCheck,
    )
    from src.models.contracts.editor import (  # noqa: F401
        AffectedEntity,
        AvailableReplacement,
        FileConflictResponse,
        FileContentRequest,
        FileContentResponse,
        FileDiagnostic,
        FileMetadata,
        FileType,
        FileStatResponse,
        PendingDeactivation,
        ScriptExecutionRequest,
        ScriptExecutionResponse,
        SearchRequest,
        SearchResponse,
        SearchResult,
        WorkflowDeactivationConflict,
        WorkflowIdConflict,
    )
    from src.models.contracts.files import (  # noqa: F401
        FilePullRequest,
        FilePullResponse,
        WatchSessionRequest,
    )
    from src.models.contracts.common import (  # noqa: F401
        BrandingSettings,
        BrandingTerm,
        BrandingTerminology,
        BrandingUpdateRequest,
        ErrorResponse,
        FileUploadRequest,
        FileUploadResponse,
        InstallPackageRequest,
        InstalledPackage,
        InstalledPackagesResponse,
        PackageInstallResponse,
        PackageUpdate,
        PackageUpdatesResponse,
        UploadedFileMetadata,
    )
    from src.models.contracts.scheduling import (  # noqa: F401
        AsyncExecution,
        AsyncExecutionStatus,
        CronValidationRequest,
        CronValidationResponse,
    )
    from src.models.contracts.github import (  # noqa: F401
        CommitAndPushRequest,
        CommitAndPushResponse,
        CommitHistoryResponse,
        CommitInfo,
        CompatibleReplacement,
        CompatibleReplacementsResponse,
        ConflictInfo,
        CreateRepoRequest,
        CreateRepoResponse,
        DeactivateWorkflowResponse,
        DetectedRepoInfo,
        FetchFromGitHubResponse,
        FileChange,
        GitFileStatus,
        GitHubBranchInfo,
        GitHubBranchesResponse,
        GitHubConfigEntity,
        GitHubConfigRequest,
        GitHubConfigResponse,
        GitHubRepoInfo,
        GitHubReposResponse,
        GitHubSetupResponse,
        GitRefreshStatusResponse,
        OrphanedWorkflowInfo,
        OrphanedWorkflowsResponse,
        OrphanInfo,
        PreflightIssue,
        PreflightResult,
        RecreateFileResponse,
        RemapWorkflowRequest,
        RemapWorkflowResponse,
        ReplaceWorkflowRequest,
        ReplaceWorkflowResponse,
        ValidateTokenRequest,
        WorkflowReference,
        WorkspaceAnalysisResponse,
        GitJobResponse,
        GitOpRequest,
        SyncRequest,
        CommitRequest,
        ResolveRequest,
        DiffRequest,
        DiscardRequest,
        DiscardResult,
        ConfirmDeletionsRequest,
        ConfirmDeletionsResult,
        ChangedFile,
        MergeConflict,
        FetchResult,
        WorkingTreeStatus,
        CommitResult,
        PullResult,
        PushResult,
        RepoStatusResponse,
        ResolveResult,
        SyncResult,
        AbortMergeResult,
        DiffResult,
        SyncExecuteRequest,
    )
    from src.models.contracts.cli import (  # noqa: F401
        CLIConfigDeleteRequest,
        CLIConfigGetRequest,
        CLIConfigListRequest,
        CLIConfigSetRequest,
        CLIConfigValue,
        CLIFileDeleteRequest,
        CLIFileListRequest,
        CLIFileReadRequest,
        CLIFileWriteRequest,
        CLIRegisteredWorkflow,
        CLISessionContinueRequest,
        CLISessionContinueResponse,
        CLISessionExecutionSummary,
        CLISessionListResponse,
        CLISessionLogRequest,
        CLISessionPendingResponse,
        CLISessionRegisterRequest,
        CLISessionResponse,
        CLISessionResultRequest,
    )
    from src.models.contracts.sdk import (  # noqa: F401
        ConfigData,
        IntegrationData,
        OAuthCredentials as SDKOAuthCredentials,
    )
    from src.models.contracts.profile import (  # noqa: F401
        PasswordChange,
        ProfileResponse,
        ProfileUpdate,
    )
    from src.models.contracts.memory import (  # noqa: F401
        MemoryDeleteResponse,
        MemoryEntryList,
        MemoryEntryPublic,
        MemoryPlatformSettings,
        MemoryPlatformSettingsUpdate,
        MemorySaveRequest,
        MemorySearchRequest,
        MemorySearchResponse,
        MemorySearchResult,
        MemoryUserSettings,
        MemoryUserSettingsUpdate,
    )
    from src.models.contracts.required_instructions import (  # noqa: F401
        RequiredInstructionsResponse,
        RequiredInstructionsSettings,
    )
    from src.models.contracts.kubernetes import (  # noqa: F401
        KubernetesExecutionJobType,
        KubernetesExecutionSettings,
        KubernetesExecutionUpdate,
        KubernetesStatus,
    )
    from src.models.contracts.notifications import (  # noqa: F401
        JobDispatchResponse,
        NotificationCategory,
        NotificationCreate,
        NotificationListResponse,
        NotificationPublic,
        NotificationStatus,
        NotificationUpdate,
        UploadLockInfo,
    )
    from src.models.contracts.external_mcp import (  # noqa: F401
        MCPServerCreate,
        MCPServerUpdate,
        MCPServerSummary,
        MCPServerPublic,
        MCPConnectionCreate,
        MCPConnectionUpdate,
        MCPConnectionSummary,
        MCPConnectionPublic,
        MCPConnectionToolCreate,
        MCPConnectionToolUpdate,
        MCPConnectionToolPublic,
        UserMCPCredentialCreate,
        UserMCPCredentialPublic,
    )
    from src.models.contracts.integrations import (  # noqa: F401
        ConfigSchemaItem,
        ConfigItemType,
        IntegrationCreate,
        IntegrationUpdate,
        IntegrationResponse,
        IntegrationDetailResponse,
        IntegrationListResponse,
        IntegrationMappingCreate,
        IntegrationMappingUpdate,
        IntegrationMappingBatchItem,
        IntegrationMappingBatchRequest,
        IntegrationMappingBatchResponse,
        IntegrationMappingResponse,
        IntegrationMappingListResponse,
        EntityIdSourceUpdateRequest,
        MappingAuthorizeRequest,
        MappingAuthorizeResponse,
        OAuthConfigSummary,
        IntegrationTestRequest,
        IntegrationTestResponse,
    )
    from src.models.contracts.decorators import (  # noqa: F401
        DecoratorInfo,
        DecoratorPropertiesResponse,
        DecoratorType,
        UpdatePropertiesRequest,
        UpdatePropertiesResponse,
    )
    from src.models.contracts.maintenance import (  # noqa: F401
        CleanupOrphanedResponse,
        DocsIndexResponse,
        MaintenanceStatus,
        OrphanedEntity,
        PreflightIssueResponse,
        PreflightResponse,
        ReimportJobResponse,
    )
    from src.models.contracts.roi import (  # noqa: F401
        ROISettingsRequest,
        ROISettingsResponse,
        ROISummaryResponse,
        WorkflowROIEntry,
        ROIByWorkflowResponse,
        OrganizationROIEntry,
        ROIByOrganizationResponse,
        ROITrendEntry,
        ROITrendsResponse,
    )
    from src.models.contracts.ai_usage import (  # noqa: F401
        AIModelPricingBase,
        AIModelPricingCreate,
        AIModelPricingUpdate,
        AIModelPricingPublic,
        AIModelPricingListItem,
        AIModelPricingListResponse,
        AIUsageBase,
        AIUsagePublic,
        AIUsageTotals,
        AIUsageByModel,
        AIUsageSummaryResponse,
        UsageReportSummary,
        UsageTrend,
        WorkflowUsage,
        ConversationUsage,
        AgentUsage,
        OrganizationUsage,
        KnowledgeStorageUsage,
        KnowledgeStorageTrend,
        UsageReportResponse,
    )
    from src.models.contracts.export_import import (  # noqa: F401
        BulkExportRequest,
        ConfigExportFile,
        ExportMetadata,
        ImportResult,
        ImportResultItem,
        IntegrationExportFile,
        KnowledgeExportFile,
        TableExportFile,
    )
    from src.models.contracts.dependencies import (  # noqa: F401
        DependencyAvailabilityRequest,
        DependencyAvailabilityResponse,
    )
    from src.models.contracts.platform import (  # noqa: F401
        PoolDetail,
        PoolsListResponse,
        PoolStatsResponse,
        PoolSummary,
        ProcessInfo,
        QueueItem,
        QueueStatusResponse,
        RecycleProcessRequest,
        RecycleProcessResponse,
        StuckHistoryResponse,
        StuckWorkflowStats,
    )

__all__ = list(CONTRACT_ALL)


def __getattr__(name: str) -> Any:
    export = CONTRACT_EXPORTS.get(name)
    if export is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    module_name, attr_name = export
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
