"""Contracts for the R2a-1 access list.

The access list is the single hand-curated inventory of who can reach every
HTTP route and MCP tool today. It records the intended access class, the
gate the code actually enforces right now (mechanically derivable from the
dependency tree / MCP transport), and — for permission-class entries — the
permission string and boundary that will eventually gate it once the R2/R3
roles catalog is wired in.

This module is contracts only. The data lives in
``src.services.access_list``; the JSON projection is generated by
``scripts/generate_access_list.py``.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, model_validator

from src.models.contracts.permissions import parse_permission


class AccessClass(StrEnum):
    """The kind of access a route or MCP tool grants."""

    # No authentication required (login, OAuth/device flows, health, CLI
    # download, inbound webhooks).
    PUBLIC = "public"
    # Authenticated user acting on their own data (profile, MFA, sessions,
    # chat, home, notifications, memory, own OAuth connections).
    PERSONAL = "personal"
    # Running something that already exists (a form, an app, a workflow, an
    # agent run, an MCP gateway tool) rather than managing its definition.
    EXECUTE = "execute"
    # Agent create/update/delete limited to the caller's own private agent.
    OWN_PRIVATE_AGENT = "own_private_agent"
    # Table row / repository file data whose access is governed by the
    # table-policy or file-policy engine, not by this list.
    TABLE_POLICY = "table_policy"
    # An embed-session-only surface (iframe embedding).
    EMBED = "embed"
    # A platform-managed entity read or write gated by an eventual
    # permission string + boundary (the R2/R3 roles-catalog target shape).
    PERMISSION = "permission"


class CurrentGate(StrEnum):
    """What the code's DEPENDENCY TREE enforces today — mechanically derived,
    never overridden by an inline check. An inline check the handler (or a
    service it calls one level down) layers on top is recorded separately on
    ``AccessEntry.inline_checks``; it never changes this value."""

    # No auth dependency at all.
    NONE = "none"
    # CurrentUser / CurrentActiveUser / Context (any signed-in user).
    AUTHENTICATED = "authenticated"
    # CurrentSuperuser / RequirePlatformAdmin / get_current_superuser.
    SUPERUSER = "superuser"
    # CurrentEngineOrBypassUser (execution credentials or scope-bypass admin).
    ENGINE_OR_BYPASS = "engine_or_bypass"
    # An engine-token-only dependency (narrower than engine_or_bypass: no
    # human scope-bypass admission).
    ENGINE = "engine"
    # An embed-session-only dependency.
    EMBED = "embed"
    # CurrentActiveUser (any signed-in user) plus the R3 enforcement helper
    # (``src.services.authorization.enforce``), which decides this entry's
    # permission and boundary with the evaluator. The route has been cut over:
    # the dependency tree alone shows ``authenticated``; the gate-agreement
    # test checks the handler calls the helper with this entry's operation.
    EVALUATOR = "evaluator"


class InlineEffect(StrEnum):
    """What an inline check does to the caller, once the entry's
    ``inline_checks`` tokens (or a deeper check the one-hop scan cannot see)
    have been read against the handler and the service it calls. The R2c
    evaluator and its legacy oracle both read this to decide how an entry
    behaves for a caller acting beyond their own organization."""

    # The handler refuses non-superusers outright.
    DENY_UNLESS_SUPERUSER = "deny_unless_superuser"
    # The handler refuses callers without scope bypass (superuser or
    # provider-org member).
    DENY_UNLESS_BYPASS = "deny_unless_bypass"
    # Everyone signed in reaches it; superusers additionally act beyond
    # their own organization or see everything.
    WIDENS_FOR_SUPERUSER = "widens_for_superuser"
    # Same, for a superuser or a provider-org member.
    WIDENS_FOR_BYPASS = "widens_for_bypass"
    # The token is present but does not gate the caller (for example it is
    # copied into a claim or a response).
    NO_CALLER_EFFECT = "no_caller_effect"


# The specific inline-check tokens the gate-agreement test looks for in the
# handler's source (or the source of a function it calls one level down):
# is_superuser / is_platform_admin / has_scope_bypass / is_provider_org /
# mcp_write_scope_bypass (the MCP-tool analog of has_scope_bypass, used by
# the code_editor tools' `_check_read_scope` / `_check_write_scope`).
INLINE_CHECK_TOKENS = (
    "is_superuser",
    "is_platform_admin",
    "has_scope_bypass",
    "is_provider_org",
    "mcp_write_scope_bypass",
)


_PERMISSION_BOUNDARIES = ("organization", "managed_organizations", "platform")


class AccessEntry(BaseModel):
    """One route or MCP tool's checked-in access record."""

    model_config = ConfigDict(frozen=True)

    method: str | None = None
    path: str | None = None
    mcp_tool: str | None = None

    access_class: AccessClass
    current_gate: CurrentGate

    # Inline is_superuser/is_platform_admin/has_scope_bypass/is_provider_org/
    # mcp_write_scope_bypass tokens actually found in the handler's source
    # (or a function it calls one level down), beyond current_gate's
    # dependency-tree check. Empty when there is none.
    inline_checks: tuple[str, ...] = ()

    # What the inline check does to the caller. Required when
    # ``inline_checks`` is non-empty; may also be set with empty
    # ``inline_checks`` when the check lives deeper than the one-hop scan (the
    # ``reason`` then says where).
    inline_effect: InlineEffect | None = None

    # Required iff access_class is PERMISSION. Format:
    # "<domain>.<read|readwrite|execute>[.all]" (see parse_permission).
    permission: str | None = None
    # Required iff access_class is PERMISSION.
    boundary: str | None = None

    # The operation-catalog id, when this route/tool is catalogued.
    operation_id: str | None = None

    # One line: why this class/gate.
    reason: str

    # Set only when today's gate is broader or narrower than the intended
    # class (e.g. every engine_or_bypass route used by humans today).
    intended_change: str | None = None

    @model_validator(mode="after")
    def _validate_inline_checks(self) -> "AccessEntry":
        unknown = set(self.inline_checks) - set(INLINE_CHECK_TOKENS)
        if unknown:
            raise ValueError(f"unknown inline_checks tokens: {sorted(unknown)}")
        return self

    @model_validator(mode="after")
    def _validate_inline_effect(self) -> "AccessEntry":
        if self.inline_checks and self.inline_effect is None:
            raise ValueError("inline_effect is required when inline_checks is non-empty")
        return self

    @model_validator(mode="after")
    def _validate_target(self) -> "AccessEntry":
        has_rest = self.method is not None or self.path is not None
        has_mcp = self.mcp_tool is not None
        if has_rest and has_mcp:
            raise ValueError("AccessEntry may not set both method/path and mcp_tool")
        if not has_rest and not has_mcp:
            raise ValueError("AccessEntry must set either method+path or mcp_tool")
        if has_rest and (self.method is None or self.path is None):
            raise ValueError("AccessEntry with method/path must set both")
        return self

    @model_validator(mode="after")
    def _validate_permission(self) -> "AccessEntry":
        if self.access_class == AccessClass.PERMISSION:
            if not self.permission:
                raise ValueError("permission is required when access_class is 'permission'")
            if not self.boundary:
                raise ValueError("boundary is required when access_class is 'permission'")
            if self.boundary not in _PERMISSION_BOUNDARIES:
                raise ValueError(f"boundary must be one of {_PERMISSION_BOUNDARIES}")
            parse_permission(self.permission)
        else:
            if self.permission is not None or self.boundary is not None:
                raise ValueError(
                    "permission/boundary must be unset unless access_class is 'permission'"
                )
        return self

    @property
    def key(self) -> tuple[str, str] | str:
        """A stable identity for completeness/uniqueness checks."""
        if self.mcp_tool is not None:
            return self.mcp_tool
        assert self.method is not None and self.path is not None
        return (self.method, self.path)
