apiVersion: v1
kind: ServiceAccount
metadata:
  name: bifrost-build-controller
  namespace: bifrost
  labels:
    app.kubernetes.io/name: bifrost-build-controller
    app.kubernetes.io/component: build-controller
    app.kubernetes.io/part-of: bifrost
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bifrost-build-runner
  namespace: bifrost
  labels:
    app.kubernetes.io/name: bifrost-build-runner
    app.kubernetes.io/component: build-runner
    app.kubernetes.io/part-of: bifrost
automountServiceAccountToken: false

