apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - api/deployment.yaml
  - api/service.yaml
  - client/deployment.yaml
  - client/service.yaml
  - worker/deployment.yaml
  - scheduler/deployment.yaml
  - builder/deployment.yaml
  - builder-runner/deployment.yaml
  - builder-runner/service.yaml
  - builder-runner/network-policy.yaml
  - app-host/deployment.yaml
  - app-host/service.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
