"""E2E: GET /api/solutions/{id}/setup — required-config setup status.

Verifies that the endpoint returns a ``setup_complete`` flag and an ``items``
list that includes each SolutionConfigSchema declaration paired with whether a
matching Config value is set in the install's org scope.

"""
from __future__ import annotations

import io
import uuid
import zipfile

import pytest

from tests.e2e.platform.conftest import wait_for_install

pytestmark = pytest.mark.e2e


def _make_endpoint_workflow_zip(slug: str) -> bytes:
    wf_id = str(uuid.uuid5(uuid.NAMESPACE_URL, f"{slug}/workflows/endpoint"))
    files = {
        "bifrost.solution.yaml": f"slug: {slug}\nname: {slug.upper()}\nscope: global\n",
        ".bifrost/workflows.yaml": (
            "workflows:\n"
            f"  {wf_id}:\n"
            f"    id: {wf_id}\n"
            "    name: Ticket Webhook\n"
            "    function_name: ticket_webhook\n"
            "    path: workflows/ticket_webhook.py\n"
            "    endpoint_enabled: true\n"
            "    allowed_methods: [GET, POST]\n"
            "    public_endpoint: false\n"
        ),
        "workflows/ticket_webhook.py": (
            "from bifrost import workflow\n\n"
            "@workflow(name='Ticket Webhook')\n"
            "async def ticket_webhook(source: str = 'manual') -> dict:\n"
            "    return {'ok': True, 'source': source, 'workflow': 'Ticket Webhook'}\n"
        ),
    }
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as z:
        for name, content in files.items():
            z.writestr(name, content)
    return buf.getvalue()


async def test_setup_status_lists_required_unset_configs(
    e2e_client, platform_admin, make_solution_with_required_config
):
    sol = await make_solution_with_required_config(key="api_key", required=True)
    headers = platform_admin.headers
    resp = e2e_client.get(f"/api/solutions/{sol['id']}/setup", headers=headers)
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["setup_complete"] is False
    keys = {i["key"]: i for i in body["items"]}
    assert keys["api_key"]["is_set"] is False
    assert keys["api_key"]["required"] is True
    # The declaration's default rides along for the setup wizard.
    assert keys["api_key"]["default"] == "a-default"


async def test_setup_status_marks_set_config_complete(
    e2e_client, platform_admin, make_solution_with_required_config
):
    sol = await make_solution_with_required_config(
        key="api_key", required=True, set_value=True
    )
    headers = platform_admin.headers
    resp = e2e_client.get(f"/api/solutions/{sol['id']}/setup", headers=headers)
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["setup_complete"] is True
    keys = {i["key"]: i for i in body["items"]}
    assert keys["api_key"]["is_set"] is True
    assert keys["api_key"]["required"] is True


async def test_setup_status_no_declarations_is_complete(
    e2e_client, platform_admin, make_solution_without_configs
):
    """Vacuous-true guard: an install with no config declarations is complete."""
    sol = await make_solution_without_configs()
    headers = platform_admin.headers
    resp = e2e_client.get(f"/api/solutions/{sol['id']}/setup", headers=headers)
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["setup_complete"] is True
    assert body["items"] == []

async def test_non_public_endpoint_workflow_setup_requires_generated_key(
    e2e_client, platform_admin
):
    headers = platform_admin.headers
    upload_headers = {k: v for k, v in headers.items() if k.lower() != "content-type"}
    slug = f"setup-endpoint-key-{uuid.uuid4().hex[:8]}"

    installed = wait_for_install(
        e2e_client,
        e2e_client.post(
            "/api/solutions/install",
            headers=upload_headers,
            files={"file": ("endpoint.zip", _make_endpoint_workflow_zip(slug), "application/zip")},
        ),
        headers,
    )
    assert installed.status_code in (200, 201), installed.text
    body = installed.json()
    assert body["setup_complete"] is False

    setup = e2e_client.get(f"/api/solutions/{body['id']}/setup", headers=headers)
    assert setup.status_code == 200, setup.text
    setup_body = setup.json()
    endpoint_items = [
        i for i in setup_body["items"] if i["kind"] == "workflow_endpoint_key"
    ]
    assert len(endpoint_items) == 1
    item = endpoint_items[0]
    assert item["workflow_name"] == "Ticket Webhook"
    assert item["allowed_methods"] == ["GET", "POST"]
    assert item["is_set"] is False

    created = e2e_client.post(
        "/api/workflow-keys",
        headers=headers,
        json={
            "workflow_id": item["workflow_id"],
            "description": "generated by setup e2e",
        },
    )
    assert created.status_code == 201, created.text
    assert created.json()["raw_key"]

    executed = e2e_client.post(
        f"/api/endpoints/{item['workflow_id']}",
        headers={"X-Bifrost-Key": created.json()["raw_key"]},
        json={"source": "solution-e2e"},
        timeout=60.0,
    )
    assert executed.status_code == 200, executed.text
    execution_body = executed.json()
    assert execution_body["status"] == "Success"
    assert execution_body["result"] == {
        "ok": True,
        "source": "solution-e2e",
        "workflow": "Ticket Webhook",
    }

    setup_after = e2e_client.get(f"/api/solutions/{body['id']}/setup", headers=headers)
    assert setup_after.status_code == 200, setup_after.text
    after_body = setup_after.json()
    assert after_body["setup_complete"] is True
    after_item = [
        i for i in after_body["items"] if i["kind"] == "workflow_endpoint_key"
    ][0]
    assert after_item["is_set"] is True

    solution_after = e2e_client.get(f"/api/solutions/{body['id']}", headers=headers)
    assert solution_after.status_code == 200, solution_after.text
    assert solution_after.json()["setup_complete"] is True

    revoked = e2e_client.delete(
        f"/api/workflow-keys/{item['workflow_id']}",
        headers=headers,
    )
    assert revoked.status_code == 204, revoked.text

    setup_revoked = e2e_client.get(f"/api/solutions/{body['id']}/setup", headers=headers)
    assert setup_revoked.status_code == 200, setup_revoked.text
    assert setup_revoked.json()["setup_complete"] is False
    solution_revoked = e2e_client.get(f"/api/solutions/{body['id']}", headers=headers)
    assert solution_revoked.status_code == 200, solution_revoked.text
    assert solution_revoked.json()["setup_complete"] is False
