"""Static export registries for lazy model package exports."""


CONTRACT_ALL: tuple[str, ...] = (
    'RetryPolicy',
    'DataProviderInputMode',
    'IntegrationType',
    'generate_entity_id',
    'DependencyAvailabilityRequest',
    'DependencyAvailabilityResponse',
    'CreateOrganizationRequest',
    'UpdateOrganizationRequest',
    'OrganizationBase',
    'OrganizationCreate',
    'OrganizationUpdate',
    'OrganizationPublic',
    'CreateUserRequest',
    'UpdateUserRequest',
    'UserBase',
    'UserCreate',
    'UserUpdate',
    'UserPublic',
    'UserResponse',
    'BulkUserFailure',
    'BulkUserOperation',
    'BulkUserResponse',
    'CreateRoleRequest',
    'UpdateRoleRequest',
    'RoleBase',
    'RoleCreate',
    'RoleUpdate',
    'RolePublic',
    'RoleUserSummary',
    'UserPermission',
    'PermissionsData',
    'GrantPermissionsRequest',
    'UserRolesResponse',
    'UserFormsResponse',
    'RoleUsersResponse',
    'RoleFormsResponse',
    'RoleAppsResponse',
    'RoleWorkflowsResponse',
    'RoleKnowledgeResponse',
    'RoleKnowledgeEntry',
    'RoleConsumerCounts',
    'AssignUsersToRoleRequest',
    'AssignFormsToRoleRequest',
    'AssignAppsToRoleRequest',
    'AssignWorkflowsToRoleRequest',
    'AssignKnowledgeToRoleRequest',
    'KnowledgeAssignmentInput',
    'UnassignUsersFromRoleRequest',
    'UnassignFormsFromRoleRequest',
    'UnassignAgentsFromRoleRequest',
    'UnassignAppsFromRoleRequest',
    'UnassignWorkflowsFromRoleRequest',
    'UnassignKnowledgeFromRoleRequest',
    'OAuthProviderInfo',
    'AuthStatusResponse',
    'MFARequiredResponse',
    'MFASetupRequiredResponse',
    'MFAVerifyRequest',
    'LoginResponse',
    'TokenRefresh',
    'MFASetupTokenRequest',
    'MFASetupResponse',
    'MFAEnrollVerifyRequest',
    'MFAEnrollVerifyResponse',
    'OAuthLoginRequest',
    'DeviceCodeResponse',
    'DeviceTokenRequest',
    'DeviceTokenResponse',
    'DeviceTokenErrorResponse',
    'DeviceAuthorizeRequest',
    'PasskeyRegistrationOptionsRequest',
    'PasskeyRegistrationOptionsResponse',
    'PasskeyRegistrationVerifyRequest',
    'PasskeyRegistrationVerifyResponse',
    'PasskeyAuthOptionsRequest',
    'PasskeyAuthOptionsResponse',
    'PasskeyAuthVerifyRequest',
    'PasskeyPublic',
    'PasskeyListResponse',
    'PasskeyDeleteResponse',
    'FormFieldValidation',
    'DataProviderInputConfig',
    'FormSchema',
    'CreateFormRequest',
    'UpdateFormRequest',
    'FormConfirmationResponse',
    'FormExecutionResponse',
    'FormFieldOptionsRequest',
    'FormFieldOptionsResponse',
    'FormStartupResponse',
    'FormSubmissionRequest',
    'FormSubmissionResponse',
    'FormCreate',
    'FormUpdate',
    'FormPublic',
    'FormCaptchaChallenge',
    'FormRuntimeDefinition',
    'FormPublicationPublic',
    'FormPublicationReview',
    'FormPublicationUpdate',
    'AgentCreate',
    'AgentUpdate',
    'AgentPublic',
    'AgentSummary',
    'ConversationCreate',
    'ConversationPublic',
    'ConversationSummary',
    'MessagePublic',
    'ChatRequest',
    'ChatResponse',
    'ChatStreamChunk',
    'ToolCall',
    'ToolResult',
    'AssignAgentsToRoleRequest',
    'RoleAgentsResponse',
    'ExecutionBase',
    'ExecutionLogPublic',
    'AIUsagePublicSimple',
    'AIUsageTotalsSimple',
    'WorkflowExecution',
    'WorkflowExecutionRequest',
    'WorkflowExecutionResponse',
    'ExecutionsListResponse',
    'StuckExecutionsResponse',
    'CleanupTriggeredResponse',
    'ExecutionCreate',
    'ExecutionUpdate',
    'ExecutionPublic',
    'AuditLogActor',
    'AuditLogEntry',
    'AuditLogListResponse',
    'SetConfigRequest',
    'UpdateConfigRequest',
    'ConfigBase',
    'ConfigCreate',
    'ConfigUpdate',
    'ConfigPublic',
    'ConfigResponse',
    'IntegrationConfig',
    'SetIntegrationConfigRequest',
    'SecretListResponse',
    'SecretCreateRequest',
    'SecretUpdateRequest',
    'SecretResponse',
    'SecretBase',
    'SecretCreate',
    'SecretUpdate',
    'SecretPublic',
    'HealthCheck',
    'BasicHealthResponse',
    'GeneralHealthResponse',
    'ExecutionStats',
    'RecentFailure',
    'ROISnapshot',
    'DashboardMetricsResponse',
    'ExecutionTimeSeriesBucket',
    'ExecutionTimeSeriesResponse',
    'PlatformMetricsResponse',
    'DailyMetricsEntry',
    'DailyMetricsResponse',
    'OrganizationMetricsSummary',
    'OrganizationMetricsResponse',
    'ResourceMetricsEntry',
    'ResourceMetricsResponse',
    'WorkflowMetricsSummary',
    'WorkflowMetricsResponse',
    'OAuthFlowType',
    'OAuthStatus',
    'CreateOAuthConnectionRequest',
    'UpdateOAuthConnectionRequest',
    'OAuthConnectionSummary',
    'OAuthConnectionDetail',
    'OAuthConnection',
    'OAuthCredentials',
    'OAuthCredentialsModel',
    'OAuthCredentialsResponse',
    'EntityIdPickerCandidate',
    'OAuthCallbackRequest',
    'OAuthCallbackResponse',
    'OAuthProviderBase',
    'OAuthProviderCreate',
    'OAuthProviderUpdate',
    'OAuthProviderPublic',
    'FileUploadRequest',
    'FileUploadResponse',
    'UploadedFileMetadata',
    'WorkflowKey',
    'WorkflowKeyCreateRequest',
    'WorkflowKeyResponse',
    'AsyncExecution',
    'AsyncExecutionStatus',
    'CronValidationRequest',
    'CronValidationResponse',
    'BrandingSettings',
    'BrandingTerm',
    'BrandingTerminology',
    'BrandingUpdateRequest',
    'FileType',
    'FileMetadata',
    'FileContentRequest',
    'FileContentResponse',
    'FileConflictResponse',
    'FileStatResponse',
    'FileDiagnostic',
    'WorkflowIdConflict',
    'AffectedEntity',
    'PendingDeactivation',
    'AvailableReplacement',
    'WorkflowDeactivationConflict',
    'SearchRequest',
    'SearchResult',
    'SearchResponse',
    'ScriptExecutionRequest',
    'ScriptExecutionResponse',
    'InstallPackageRequest',
    'PackageInstallResponse',
    'InstalledPackage',
    'InstalledPackagesResponse',
    'PackageUpdate',
    'PackageUpdatesResponse',
    'GitFileStatus',
    'FileChange',
    'ConflictInfo',
    'ValidateTokenRequest',
    'GitHubConfigRequest',
    'GitHubConfigResponse',
    'GitHubRepoInfo',
    'GitHubReposResponse',
    'GitHubBranchInfo',
    'WorkspaceAnalysisResponse',
    'CreateRepoRequest',
    'CreateRepoResponse',
    'GitHubBranchesResponse',
    'CommitAndPushRequest',
    'CommitAndPushResponse',
    'FetchFromGitHubResponse',
    'GitHubSetupResponse',
    'GitRefreshStatusResponse',
    'RepoStatusResponse',
    'CommitHistoryResponse',
    'CommitInfo',
    'DetectedRepoInfo',
    'GitHubConfigEntity',
    'PreflightIssue',
    'PreflightResult',
    'WorkflowReference',
    'OrphanInfo',
    'OrphanedWorkflowInfo',
    'OrphanedWorkflowsResponse',
    'CompatibleReplacement',
    'CompatibleReplacementsResponse',
    'ReplaceWorkflowRequest',
    'ReplaceWorkflowResponse',
    'RemapWorkflowRequest',
    'RemapWorkflowResponse',
    'RecreateFileResponse',
    'DeactivateWorkflowResponse',
    'GitJobResponse',
    'GitOpRequest',
    'SyncRequest',
    'CommitRequest',
    'ResolveRequest',
    'DiffRequest',
    'DiscardRequest',
    'DiscardResult',
    'ConfirmDeletionsRequest',
    'ConfirmDeletionsResult',
    'ChangedFile',
    'MergeConflict',
    'FetchResult',
    'WorkingTreeStatus',
    'CommitResult',
    'PullResult',
    'PushResult',
    'ResolveResult',
    'SyncResult',
    'AbortMergeResult',
    'DiffResult',
    'SyncExecuteRequest',
    'CLIFileReadRequest',
    'CLIFileWriteRequest',
    'CLIFileListRequest',
    'CLIFileDeleteRequest',
    'CLIConfigGetRequest',
    'CLIConfigSetRequest',
    'CLIConfigListRequest',
    'CLIConfigDeleteRequest',
    'CLIConfigValue',
    'CLIRegisteredWorkflow',
    'CLISessionRegisterRequest',
    'CLISessionResponse',
    'CLISessionListResponse',
    'CLISessionContinueRequest',
    'CLISessionContinueResponse',
    'CLISessionPendingResponse',
    'CLISessionLogRequest',
    'CLISessionResultRequest',
    'CLISessionExecutionSummary',
    'ErrorResponse',
    'WorkflowParameter',
    'WorkflowMetadata',
    'DataProviderMetadata',
    'MetadataResponse',
    'FormDiscoveryMetadata',
    'RegisterWorkflowRequest',
    'RegisterWorkflowResponse',
    'ValidationIssue',
    'WorkflowUpdateRequest',
    'WorkflowValidationRequest',
    'WorkflowValidationResponse',
    'EntityUsage',
    'WorkflowUsageStats',
    'WorkflowRolesResponse',
    'AssignRolesToWorkflowRequest',
    'DeleteWorkflowRequest',
    'DataProviderRequest',
    'DataProviderOption',
    'DataProviderResponse',
    'NotificationCategory',
    'NotificationStatus',
    'NotificationCreate',
    'NotificationUpdate',
    'NotificationPublic',
    'NotificationListResponse',
    'JobDispatchResponse',
    'UploadLockInfo',
    'ProfileUpdate',
    'PasswordChange',
    'ProfileResponse',
    'MemoryDeleteResponse',
    'MemoryEntryList',
    'MemoryEntryPublic',
    'MemoryPlatformSettings',
    'MemoryPlatformSettingsUpdate',
    'MemorySaveRequest',
    'MemorySearchRequest',
    'MemorySearchResponse',
    'MemorySearchResult',
    'MemoryUserSettings',
    'MemoryUserSettingsUpdate',
    'KubernetesStatus',
    'KubernetesExecutionJobType',
    'KubernetesExecutionSettings',
    'KubernetesExecutionUpdate',
    'RequiredInstructionsResponse',
    'RequiredInstructionsSettings',
    'MCPServerCreate',
    'MCPServerUpdate',
    'MCPServerSummary',
    'MCPServerPublic',
    'MCPConnectionCreate',
    'MCPConnectionUpdate',
    'MCPConnectionSummary',
    'MCPConnectionPublic',
    'MCPConnectionToolCreate',
    'MCPConnectionToolUpdate',
    'MCPConnectionToolPublic',
    'UserMCPCredentialCreate',
    'UserMCPCredentialPublic',
    'ConfigItemType',
    'ConfigSchemaItem',
    'IntegrationCreate',
    'IntegrationUpdate',
    'IntegrationResponse',
    'IntegrationDetailResponse',
    'IntegrationListResponse',
    'IntegrationMappingCreate',
    'IntegrationMappingUpdate',
    'IntegrationMappingBatchItem',
    'IntegrationMappingBatchRequest',
    'IntegrationMappingBatchResponse',
    'IntegrationMappingResponse',
    'IntegrationMappingListResponse',
    'EntityIdSourceUpdateRequest',
    'MappingAuthorizeRequest',
    'MappingAuthorizeResponse',
    'IntegrationData',
    'IntegrationTestRequest',
    'IntegrationTestResponse',
    'OAuthConfigSummary',
    'DecoratorType',
    'DecoratorInfo',
    'DecoratorPropertiesResponse',
    'UpdatePropertiesRequest',
    'UpdatePropertiesResponse',
    'CleanupOrphanedResponse',
    'DocsIndexResponse',
    'MaintenanceStatus',
    'OrphanedEntity',
    'PreflightIssueResponse',
    'PreflightResponse',
    'ReimportJobResponse',
    'ROISettingsRequest',
    'ROISettingsResponse',
    'ROISummaryResponse',
    'WorkflowROIEntry',
    'ROIByWorkflowResponse',
    'OrganizationROIEntry',
    'ROIByOrganizationResponse',
    'ROITrendEntry',
    'ROITrendsResponse',
    'AIModelPricingBase',
    'AIModelPricingCreate',
    'AIModelPricingUpdate',
    'AIModelPricingPublic',
    'AIModelPricingListItem',
    'AIModelPricingListResponse',
    'AIUsageBase',
    'AIUsagePublic',
    'AIUsageTotals',
    'AIUsageByModel',
    'AIUsageSummaryResponse',
    'UsageReportSummary',
    'UsageTrend',
    'WorkflowUsage',
    'ConversationUsage',
    'AgentUsage',
    'OrganizationUsage',
    'KnowledgeStorageUsage',
    'KnowledgeStorageTrend',
    'UsageReportResponse',
    'ConfigData',
    'IntegrationData',
    'SDKOAuthCredentials',
    'ApplicationCreate',
    'ApplicationUpdate',
    'ApplicationPublic',
    'ApplicationListResponse',
    'ApplicationDefinition',
    'ApplicationDraftSave',
    'ApplicationPublishRequest',
    'ApplicationRollbackRequest',
    'VersionHistoryEntry',
    'VersionHistoryResponse',
    'AppFileCreate',
    'AppFileUpdate',
    'AppFileResponse',
    'AppFileListResponse',
    'PlatformJobAccepted',
    'PlatformJobCancelResponse',
    'PlatformJobError',
    'PlatformJobListResponse',
    'PlatformJobProgress',
    'PlatformJobPublic',
    'PlatformJobStatus',
    'SchedulerCapacityStatus',
    'SchedulerDiagnosticsResponse',
    'SchedulerLeaderStatus',
    'SchedulerReplicaStatus',
    'SchedulerTaskRunStatus',
    'SchedulerTaskStatus',
    'SystemDiagnosticLogPublic',
    'PoolDetail',
    'PoolsListResponse',
    'PoolStatsResponse',
    'PoolSummary',
    'ProcessInfo',
    'QueueItem',
    'QueueStatusResponse',
    'RecycleProcessRequest',
    'RecycleProcessResponse',
    'StuckHistoryResponse',
    'StuckWorkflowStats',
    'FilePullRequest',
    'FilePullResponse',
    'WatchSessionRequest',
    'ExportMetadata',
    'KnowledgeExportFile',
    'TableExportFile',
    'ConfigExportFile',
    'IntegrationExportFile',
    'BulkExportRequest',
    'ImportResult',
    'ImportResultItem',
    'AIConnectionTestResponse',
    'AIModelAssignmentKey',
    'AIModelAssignmentResponse',
    'AIModelAssignmentUpdate',
    'AIModelProfileCreate',
    'AIModelProfileMergeRequest',
    'AIModelProfileMergeResponse',
    'AIModelProfileResponse',
    'AIModelProfileUpdate',
    'AIModelsResponse',
    'AIProviderConnectionCreate',
    'AIProviderConnectionResponse',
    'AIProviderConnectionSummary',
    'AIProviderConnectionUpdate',
    'AIProviderKind',
)

ORM_EXPORTS: tuple[str, ...] = (
    'Base',
    'Organization',
    'Solution',
    'User',
    'Role',
    'UserRole',
    'Form',
    'FormField',
    'FormRole',
    'FormPublication',
    'Agent',
    'AgentTool',
    'AgentDelegation',
    'AgentRole',
    'Conversation',
    'Message',
    'AIModelPricing',
    'AIUsage',
    'Execution',
    'ExecutionLog',
    'CLISession',
    'Config',
    'Workflow',
    'ServiceDefinition',
    'ServiceAttempt',
    'ServiceLog',
    'OAuthProvider',
    'OAuthToken',
    'Integration',
    'IntegrationMapping',
    'AuditLog',
    'UserMFAMethod',
    'MFARecoveryCode',
    'TrustedDevice',
    'UserOAuthAccount',
    'SystemConfig',
    'GlobalBranding',
    'ExecutionMetricsDaily',
    'PlatformMetricsSnapshot',
    'WorkflowROIDaily',
    'FileIndex',
    'Application',
    'PlatformJob',
    'SchedulerLease',
    'SchedulerReplica',
    'SchedulerTaskRun',
    'SchedulerTaskState',
    'SystemDiagnosticLog',
    'AppRole',
)

ENUM_EXPORTS: tuple[str, ...] = (
    'ExecutionStatus',
    'FormAccessLevel',
    'FormFieldType',
    'ConfigType',
    'MFAMethodType',
    'MFAMethodStatus',
)

CONTRACT_EXPORTS: dict[str, tuple[str, str]] = {
    'RetryPolicy': ('src.models.contracts.base', 'RetryPolicy'),
    'DataProviderInputMode': ('src.models.contracts.base', 'DataProviderInputMode'),
    'IntegrationType': ('src.models.contracts.base', 'IntegrationType'),
    'generate_entity_id': ('src.models.contracts.base', 'generate_entity_id'),
    'DependencyAvailabilityRequest': ('src.models.contracts.dependencies', 'DependencyAvailabilityRequest'),
    'DependencyAvailabilityResponse': ('src.models.contracts.dependencies', 'DependencyAvailabilityResponse'),
    'CreateOrganizationRequest': ('src.models.contracts.organizations', 'CreateOrganizationRequest'),
    'UpdateOrganizationRequest': ('src.models.contracts.organizations', 'UpdateOrganizationRequest'),
    'OrganizationBase': ('src.models.contracts.organizations', 'OrganizationBase'),
    'OrganizationCreate': ('src.models.contracts.organizations', 'OrganizationCreate'),
    'OrganizationUpdate': ('src.models.contracts.organizations', 'OrganizationUpdate'),
    'OrganizationPublic': ('src.models.contracts.organizations', 'OrganizationPublic'),
    'CreateUserRequest': ('src.models.contracts.users', 'CreateUserRequest'),
    'UpdateUserRequest': ('src.models.contracts.users', 'UpdateUserRequest'),
    'UserBase': ('src.models.contracts.users', 'UserBase'),
    'UserCreate': ('src.models.contracts.users', 'UserCreate'),
    'UserUpdate': ('src.models.contracts.users', 'UserUpdate'),
    'UserPublic': ('src.models.contracts.users', 'UserPublic'),
    'UserResponse': ('src.models.contracts.users', 'UserResponse'),
    'BulkUserFailure': ('src.models.contracts.users', 'BulkUserFailure'),
    'BulkUserOperation': ('src.models.contracts.users', 'BulkUserOperation'),
    'BulkUserResponse': ('src.models.contracts.users', 'BulkUserResponse'),
    'CreateRoleRequest': ('src.models.contracts.users', 'CreateRoleRequest'),
    'UpdateRoleRequest': ('src.models.contracts.users', 'UpdateRoleRequest'),
    'RoleBase': ('src.models.contracts.users', 'RoleBase'),
    'RoleCreate': ('src.models.contracts.users', 'RoleCreate'),
    'RoleUpdate': ('src.models.contracts.users', 'RoleUpdate'),
    'RolePublic': ('src.models.contracts.users', 'RolePublic'),
    'RoleUserSummary': ('src.models.contracts.users', 'RoleUserSummary'),
    'UserPermission': ('src.models.contracts.users', 'UserPermission'),
    'PermissionsData': ('src.models.contracts.users', 'PermissionsData'),
    'GrantPermissionsRequest': ('src.models.contracts.users', 'GrantPermissionsRequest'),
    'UserRolesResponse': ('src.models.contracts.users', 'UserRolesResponse'),
    'UserFormsResponse': ('src.models.contracts.users', 'UserFormsResponse'),
    'RoleUsersResponse': ('src.models.contracts.users', 'RoleUsersResponse'),
    'RoleFormsResponse': ('src.models.contracts.users', 'RoleFormsResponse'),
    'RoleAppsResponse': ('src.models.contracts.users', 'RoleAppsResponse'),
    'RoleWorkflowsResponse': ('src.models.contracts.users', 'RoleWorkflowsResponse'),
    'RoleKnowledgeResponse': ('src.models.contracts.users', 'RoleKnowledgeResponse'),
    'RoleKnowledgeEntry': ('src.models.contracts.users', 'RoleKnowledgeEntry'),
    'RoleConsumerCounts': ('src.models.contracts.users', 'RoleConsumerCounts'),
    'AssignUsersToRoleRequest': ('src.models.contracts.users', 'AssignUsersToRoleRequest'),
    'AssignFormsToRoleRequest': ('src.models.contracts.users', 'AssignFormsToRoleRequest'),
    'AssignAppsToRoleRequest': ('src.models.contracts.users', 'AssignAppsToRoleRequest'),
    'AssignWorkflowsToRoleRequest': ('src.models.contracts.users', 'AssignWorkflowsToRoleRequest'),
    'AssignKnowledgeToRoleRequest': ('src.models.contracts.users', 'AssignKnowledgeToRoleRequest'),
    'KnowledgeAssignmentInput': ('src.models.contracts.users', 'KnowledgeAssignmentInput'),
    'UnassignUsersFromRoleRequest': ('src.models.contracts.users', 'UnassignUsersFromRoleRequest'),
    'UnassignFormsFromRoleRequest': ('src.models.contracts.users', 'UnassignFormsFromRoleRequest'),
    'UnassignAgentsFromRoleRequest': ('src.models.contracts.users', 'UnassignAgentsFromRoleRequest'),
    'UnassignAppsFromRoleRequest': ('src.models.contracts.users', 'UnassignAppsFromRoleRequest'),
    'UnassignWorkflowsFromRoleRequest': ('src.models.contracts.users', 'UnassignWorkflowsFromRoleRequest'),
    'UnassignKnowledgeFromRoleRequest': ('src.models.contracts.users', 'UnassignKnowledgeFromRoleRequest'),
    'OAuthProviderInfo': ('src.models.contracts.auth', 'OAuthProviderInfo'),
    'AuthStatusResponse': ('src.models.contracts.auth', 'AuthStatusResponse'),
    'MFARequiredResponse': ('src.models.contracts.auth', 'MFARequiredResponse'),
    'MFASetupRequiredResponse': ('src.models.contracts.auth', 'MFASetupRequiredResponse'),
    'MFAVerifyRequest': ('src.models.contracts.auth', 'MFAVerifyRequest'),
    'LoginResponse': ('src.models.contracts.auth', 'LoginResponse'),
    'TokenRefresh': ('src.models.contracts.auth', 'TokenRefresh'),
    'MFASetupTokenRequest': ('src.models.contracts.auth', 'MFASetupTokenRequest'),
    'MFASetupResponse': ('src.models.contracts.auth', 'MFASetupResponse'),
    'MFAEnrollVerifyRequest': ('src.models.contracts.auth', 'MFAEnrollVerifyRequest'),
    'MFAEnrollVerifyResponse': ('src.models.contracts.auth', 'MFAEnrollVerifyResponse'),
    'OAuthLoginRequest': ('src.models.contracts.auth', 'OAuthLoginRequest'),
    'DeviceCodeResponse': ('src.models.contracts.auth', 'DeviceCodeResponse'),
    'DeviceTokenRequest': ('src.models.contracts.auth', 'DeviceTokenRequest'),
    'DeviceTokenResponse': ('src.models.contracts.auth', 'DeviceTokenResponse'),
    'DeviceTokenErrorResponse': ('src.models.contracts.auth', 'DeviceTokenErrorResponse'),
    'DeviceAuthorizeRequest': ('src.models.contracts.auth', 'DeviceAuthorizeRequest'),
    'PasskeyRegistrationOptionsRequest': ('src.models.contracts.passkeys', 'PasskeyRegistrationOptionsRequest'),
    'PasskeyRegistrationOptionsResponse': ('src.models.contracts.passkeys', 'PasskeyRegistrationOptionsResponse'),
    'PasskeyRegistrationVerifyRequest': ('src.models.contracts.passkeys', 'PasskeyRegistrationVerifyRequest'),
    'PasskeyRegistrationVerifyResponse': ('src.models.contracts.passkeys', 'PasskeyRegistrationVerifyResponse'),
    'PasskeyAuthOptionsRequest': ('src.models.contracts.passkeys', 'PasskeyAuthOptionsRequest'),
    'PasskeyAuthOptionsResponse': ('src.models.contracts.passkeys', 'PasskeyAuthOptionsResponse'),
    'PasskeyAuthVerifyRequest': ('src.models.contracts.passkeys', 'PasskeyAuthVerifyRequest'),
    'PasskeyPublic': ('src.models.contracts.passkeys', 'PasskeyPublic'),
    'PasskeyListResponse': ('src.models.contracts.passkeys', 'PasskeyListResponse'),
    'PasskeyDeleteResponse': ('src.models.contracts.passkeys', 'PasskeyDeleteResponse'),
    'FormFieldValidation': ('src.models.contracts.forms', 'FormFieldValidation'),
    'DataProviderInputConfig': ('src.models.contracts.forms', 'DataProviderInputConfig'),
    'FormSchema': ('src.models.contracts.forms', 'FormSchema'),
    'CreateFormRequest': ('src.models.contracts.forms', 'CreateFormRequest'),
    'UpdateFormRequest': ('src.models.contracts.forms', 'UpdateFormRequest'),
    'FormConfirmationResponse': ('src.models.contracts.forms', 'FormConfirmationResponse'),
    'FormExecutionResponse': ('src.models.contracts.forms', 'FormExecutionResponse'),
    'FormFieldOptionsRequest': ('src.models.contracts.forms', 'FormFieldOptionsRequest'),
    'FormFieldOptionsResponse': ('src.models.contracts.forms', 'FormFieldOptionsResponse'),
    'FormStartupResponse': ('src.models.contracts.forms', 'FormStartupResponse'),
    'FormSubmissionRequest': ('src.models.contracts.forms', 'FormSubmissionRequest'),
    'FormSubmissionResponse': ('src.models.contracts.forms', 'FormSubmissionResponse'),
    'FormCreate': ('src.models.contracts.forms', 'FormCreate'),
    'FormUpdate': ('src.models.contracts.forms', 'FormUpdate'),
    'FormPublic': ('src.models.contracts.forms', 'FormPublic'),
    'FormCaptchaChallenge': ('src.models.contracts.forms', 'FormCaptchaChallenge'),
    'FormRuntimeDefinition': ('src.models.contracts.forms', 'FormRuntimeDefinition'),
    'FormPublicationPublic': ('src.models.contracts.forms', 'FormPublicationPublic'),
    'FormPublicationReview': ('src.models.contracts.forms', 'FormPublicationReview'),
    'FormPublicationUpdate': ('src.models.contracts.forms', 'FormPublicationUpdate'),
    'AgentCreate': ('src.models.contracts.agents', 'AgentCreate'),
    'AgentUpdate': ('src.models.contracts.agents', 'AgentUpdate'),
    'AgentPublic': ('src.models.contracts.agents', 'AgentPublic'),
    'AgentSummary': ('src.models.contracts.agents', 'AgentSummary'),
    'ConversationCreate': ('src.models.contracts.agents', 'ConversationCreate'),
    'ConversationPublic': ('src.models.contracts.agents', 'ConversationPublic'),
    'ConversationSummary': ('src.models.contracts.agents', 'ConversationSummary'),
    'MessagePublic': ('src.models.contracts.agents', 'MessagePublic'),
    'ChatRequest': ('src.models.contracts.agents', 'ChatRequest'),
    'ChatResponse': ('src.models.contracts.agents', 'ChatResponse'),
    'ChatStreamChunk': ('src.models.contracts.agents', 'ChatStreamChunk'),
    'ToolCall': ('src.models.contracts.agents', 'ToolCall'),
    'ToolResult': ('src.models.contracts.agents', 'ToolResult'),
    'AssignAgentsToRoleRequest': ('src.models.contracts.agents', 'AssignAgentsToRoleRequest'),
    'RoleAgentsResponse': ('src.models.contracts.agents', 'RoleAgentsResponse'),
    'ExecutionBase': ('src.models.contracts.executions', 'ExecutionBase'),
    'ExecutionLogPublic': ('src.models.contracts.executions', 'ExecutionLogPublic'),
    'AIUsagePublicSimple': ('src.models.contracts.executions', 'AIUsagePublicSimple'),
    'AIUsageTotalsSimple': ('src.models.contracts.executions', 'AIUsageTotalsSimple'),
    'WorkflowExecution': ('src.models.contracts.executions', 'WorkflowExecution'),
    'WorkflowExecutionRequest': ('src.models.contracts.executions', 'WorkflowExecutionRequest'),
    'WorkflowExecutionResponse': ('src.models.contracts.executions', 'WorkflowExecutionResponse'),
    'ExecutionsListResponse': ('src.models.contracts.executions', 'ExecutionsListResponse'),
    'StuckExecutionsResponse': ('src.models.contracts.executions', 'StuckExecutionsResponse'),
    'CleanupTriggeredResponse': ('src.models.contracts.executions', 'CleanupTriggeredResponse'),
    'ExecutionCreate': ('src.models.contracts.executions', 'ExecutionCreate'),
    'ExecutionUpdate': ('src.models.contracts.executions', 'ExecutionUpdate'),
    'ExecutionPublic': ('src.models.contracts.executions', 'ExecutionPublic'),
    'AuditLogActor': ('src.models.contracts.audit', 'AuditLogActor'),
    'AuditLogEntry': ('src.models.contracts.audit', 'AuditLogEntry'),
    'AuditLogListResponse': ('src.models.contracts.audit', 'AuditLogListResponse'),
    'SetConfigRequest': ('src.models.contracts.config', 'SetConfigRequest'),
    'UpdateConfigRequest': ('src.models.contracts.config', 'UpdateConfigRequest'),
    'ConfigBase': ('src.models.contracts.config', 'ConfigBase'),
    'ConfigCreate': ('src.models.contracts.config', 'ConfigCreate'),
    'ConfigUpdate': ('src.models.contracts.config', 'ConfigUpdate'),
    'ConfigPublic': ('src.models.contracts.config', 'ConfigPublic'),
    'ConfigResponse': ('src.models.contracts.config', 'ConfigResponse'),
    'IntegrationConfig': ('src.models.contracts.config', 'IntegrationConfig'),
    'SetIntegrationConfigRequest': ('src.models.contracts.config', 'SetIntegrationConfigRequest'),
    'SecretListResponse': ('src.models.contracts.config', 'SecretListResponse'),
    'SecretCreateRequest': ('src.models.contracts.config', 'SecretCreateRequest'),
    'SecretUpdateRequest': ('src.models.contracts.config', 'SecretUpdateRequest'),
    'SecretResponse': ('src.models.contracts.config', 'SecretResponse'),
    'SecretBase': ('src.models.contracts.config', 'SecretBase'),
    'SecretCreate': ('src.models.contracts.config', 'SecretCreate'),
    'SecretUpdate': ('src.models.contracts.config', 'SecretUpdate'),
    'SecretPublic': ('src.models.contracts.config', 'SecretPublic'),
    'HealthCheck': ('src.models.contracts.health', 'HealthCheck'),
    'BasicHealthResponse': ('src.models.contracts.health', 'BasicHealthResponse'),
    'GeneralHealthResponse': ('src.models.contracts.health', 'GeneralHealthResponse'),
    'ExecutionStats': ('src.models.contracts.dashboard', 'ExecutionStats'),
    'RecentFailure': ('src.models.contracts.dashboard', 'RecentFailure'),
    'ROISnapshot': ('src.models.contracts.dashboard', 'ROISnapshot'),
    'DashboardMetricsResponse': ('src.models.contracts.dashboard', 'DashboardMetricsResponse'),
    'ExecutionTimeSeriesBucket': ('src.models.contracts.dashboard', 'ExecutionTimeSeriesBucket'),
    'ExecutionTimeSeriesResponse': ('src.models.contracts.dashboard', 'ExecutionTimeSeriesResponse'),
    'PlatformMetricsResponse': ('src.models.contracts.dashboard', 'PlatformMetricsResponse'),
    'DailyMetricsEntry': ('src.models.contracts.dashboard', 'DailyMetricsEntry'),
    'DailyMetricsResponse': ('src.models.contracts.dashboard', 'DailyMetricsResponse'),
    'OrganizationMetricsSummary': ('src.models.contracts.dashboard', 'OrganizationMetricsSummary'),
    'OrganizationMetricsResponse': ('src.models.contracts.dashboard', 'OrganizationMetricsResponse'),
    'ResourceMetricsEntry': ('src.models.contracts.dashboard', 'ResourceMetricsEntry'),
    'ResourceMetricsResponse': ('src.models.contracts.dashboard', 'ResourceMetricsResponse'),
    'WorkflowMetricsSummary': ('src.models.contracts.dashboard', 'WorkflowMetricsSummary'),
    'WorkflowMetricsResponse': ('src.models.contracts.dashboard', 'WorkflowMetricsResponse'),
    'OAuthFlowType': ('src.models.contracts.oauth', 'OAuthFlowType'),
    'OAuthStatus': ('src.models.contracts.oauth', 'OAuthStatus'),
    'CreateOAuthConnectionRequest': ('src.models.contracts.oauth', 'CreateOAuthConnectionRequest'),
    'UpdateOAuthConnectionRequest': ('src.models.contracts.oauth', 'UpdateOAuthConnectionRequest'),
    'OAuthConnectionSummary': ('src.models.contracts.oauth', 'OAuthConnectionSummary'),
    'OAuthConnectionDetail': ('src.models.contracts.oauth', 'OAuthConnectionDetail'),
    'OAuthConnection': ('src.models.contracts.oauth', 'OAuthConnection'),
    'OAuthCredentials': ('src.models.contracts.oauth', 'OAuthCredentials'),
    'OAuthCredentialsModel': ('src.models.contracts.oauth', 'OAuthCredentialsModel'),
    'OAuthCredentialsResponse': ('src.models.contracts.oauth', 'OAuthCredentialsResponse'),
    'EntityIdPickerCandidate': ('src.models.contracts.oauth', 'EntityIdPickerCandidate'),
    'OAuthCallbackRequest': ('src.models.contracts.oauth', 'OAuthCallbackRequest'),
    'OAuthCallbackResponse': ('src.models.contracts.oauth', 'OAuthCallbackResponse'),
    'OAuthProviderBase': ('src.models.contracts.oauth', 'OAuthProviderBase'),
    'OAuthProviderCreate': ('src.models.contracts.oauth', 'OAuthProviderCreate'),
    'OAuthProviderUpdate': ('src.models.contracts.oauth', 'OAuthProviderUpdate'),
    'OAuthProviderPublic': ('src.models.contracts.oauth', 'OAuthProviderPublic'),
    'FileUploadRequest': ('src.models.contracts.common', 'FileUploadRequest'),
    'FileUploadResponse': ('src.models.contracts.common', 'FileUploadResponse'),
    'UploadedFileMetadata': ('src.models.contracts.common', 'UploadedFileMetadata'),
    'WorkflowKey': ('src.models.contracts.workflows', 'WorkflowKey'),
    'WorkflowKeyCreateRequest': ('src.models.contracts.workflows', 'WorkflowKeyCreateRequest'),
    'WorkflowKeyResponse': ('src.models.contracts.workflows', 'WorkflowKeyResponse'),
    'AsyncExecution': ('src.models.contracts.scheduling', 'AsyncExecution'),
    'AsyncExecutionStatus': ('src.models.contracts.scheduling', 'AsyncExecutionStatus'),
    'CronValidationRequest': ('src.models.contracts.scheduling', 'CronValidationRequest'),
    'CronValidationResponse': ('src.models.contracts.scheduling', 'CronValidationResponse'),
    'BrandingSettings': ('src.models.contracts.common', 'BrandingSettings'),
    'BrandingTerm': ('src.models.contracts.common', 'BrandingTerm'),
    'BrandingTerminology': ('src.models.contracts.common', 'BrandingTerminology'),
    'BrandingUpdateRequest': ('src.models.contracts.common', 'BrandingUpdateRequest'),
    'FileType': ('src.models.contracts.editor', 'FileType'),
    'FileMetadata': ('src.models.contracts.editor', 'FileMetadata'),
    'FileContentRequest': ('src.models.contracts.editor', 'FileContentRequest'),
    'FileContentResponse': ('src.models.contracts.editor', 'FileContentResponse'),
    'FileConflictResponse': ('src.models.contracts.editor', 'FileConflictResponse'),
    'FileStatResponse': ('src.models.contracts.editor', 'FileStatResponse'),
    'FileDiagnostic': ('src.models.contracts.editor', 'FileDiagnostic'),
    'WorkflowIdConflict': ('src.models.contracts.editor', 'WorkflowIdConflict'),
    'AffectedEntity': ('src.models.contracts.editor', 'AffectedEntity'),
    'PendingDeactivation': ('src.models.contracts.editor', 'PendingDeactivation'),
    'AvailableReplacement': ('src.models.contracts.editor', 'AvailableReplacement'),
    'WorkflowDeactivationConflict': ('src.models.contracts.editor', 'WorkflowDeactivationConflict'),
    'SearchRequest': ('src.models.contracts.editor', 'SearchRequest'),
    'SearchResult': ('src.models.contracts.editor', 'SearchResult'),
    'SearchResponse': ('src.models.contracts.editor', 'SearchResponse'),
    'ScriptExecutionRequest': ('src.models.contracts.editor', 'ScriptExecutionRequest'),
    'ScriptExecutionResponse': ('src.models.contracts.editor', 'ScriptExecutionResponse'),
    'InstallPackageRequest': ('src.models.contracts.common', 'InstallPackageRequest'),
    'PackageInstallResponse': ('src.models.contracts.common', 'PackageInstallResponse'),
    'InstalledPackage': ('src.models.contracts.common', 'InstalledPackage'),
    'InstalledPackagesResponse': ('src.models.contracts.common', 'InstalledPackagesResponse'),
    'PackageUpdate': ('src.models.contracts.common', 'PackageUpdate'),
    'PackageUpdatesResponse': ('src.models.contracts.common', 'PackageUpdatesResponse'),
    'GitFileStatus': ('src.models.contracts.github', 'GitFileStatus'),
    'FileChange': ('src.models.contracts.github', 'FileChange'),
    'ConflictInfo': ('src.models.contracts.github', 'ConflictInfo'),
    'ValidateTokenRequest': ('src.models.contracts.github', 'ValidateTokenRequest'),
    'GitHubConfigRequest': ('src.models.contracts.github', 'GitHubConfigRequest'),
    'GitHubConfigResponse': ('src.models.contracts.github', 'GitHubConfigResponse'),
    'GitHubRepoInfo': ('src.models.contracts.github', 'GitHubRepoInfo'),
    'GitHubReposResponse': ('src.models.contracts.github', 'GitHubReposResponse'),
    'GitHubBranchInfo': ('src.models.contracts.github', 'GitHubBranchInfo'),
    'WorkspaceAnalysisResponse': ('src.models.contracts.github', 'WorkspaceAnalysisResponse'),
    'CreateRepoRequest': ('src.models.contracts.github', 'CreateRepoRequest'),
    'CreateRepoResponse': ('src.models.contracts.github', 'CreateRepoResponse'),
    'GitHubBranchesResponse': ('src.models.contracts.github', 'GitHubBranchesResponse'),
    'CommitAndPushRequest': ('src.models.contracts.github', 'CommitAndPushRequest'),
    'CommitAndPushResponse': ('src.models.contracts.github', 'CommitAndPushResponse'),
    'FetchFromGitHubResponse': ('src.models.contracts.github', 'FetchFromGitHubResponse'),
    'GitHubSetupResponse': ('src.models.contracts.github', 'GitHubSetupResponse'),
    'GitRefreshStatusResponse': ('src.models.contracts.github', 'GitRefreshStatusResponse'),
    'RepoStatusResponse': ('src.models.contracts.github', 'RepoStatusResponse'),
    'CommitHistoryResponse': ('src.models.contracts.github', 'CommitHistoryResponse'),
    'CommitInfo': ('src.models.contracts.github', 'CommitInfo'),
    'DetectedRepoInfo': ('src.models.contracts.github', 'DetectedRepoInfo'),
    'GitHubConfigEntity': ('src.models.contracts.github', 'GitHubConfigEntity'),
    'PreflightIssue': ('src.models.contracts.github', 'PreflightIssue'),
    'PreflightResult': ('src.models.contracts.github', 'PreflightResult'),
    'WorkflowReference': ('src.models.contracts.github', 'WorkflowReference'),
    'OrphanInfo': ('src.models.contracts.github', 'OrphanInfo'),
    'OrphanedWorkflowInfo': ('src.models.contracts.github', 'OrphanedWorkflowInfo'),
    'OrphanedWorkflowsResponse': ('src.models.contracts.github', 'OrphanedWorkflowsResponse'),
    'CompatibleReplacement': ('src.models.contracts.github', 'CompatibleReplacement'),
    'CompatibleReplacementsResponse': ('src.models.contracts.github', 'CompatibleReplacementsResponse'),
    'ReplaceWorkflowRequest': ('src.models.contracts.github', 'ReplaceWorkflowRequest'),
    'ReplaceWorkflowResponse': ('src.models.contracts.github', 'ReplaceWorkflowResponse'),
    'RemapWorkflowRequest': ('src.models.contracts.github', 'RemapWorkflowRequest'),
    'RemapWorkflowResponse': ('src.models.contracts.github', 'RemapWorkflowResponse'),
    'RecreateFileResponse': ('src.models.contracts.github', 'RecreateFileResponse'),
    'DeactivateWorkflowResponse': ('src.models.contracts.github', 'DeactivateWorkflowResponse'),
    'GitJobResponse': ('src.models.contracts.github', 'GitJobResponse'),
    'GitOpRequest': ('src.models.contracts.github', 'GitOpRequest'),
    'SyncRequest': ('src.models.contracts.github', 'SyncRequest'),
    'CommitRequest': ('src.models.contracts.github', 'CommitRequest'),
    'ResolveRequest': ('src.models.contracts.github', 'ResolveRequest'),
    'DiffRequest': ('src.models.contracts.github', 'DiffRequest'),
    'DiscardRequest': ('src.models.contracts.github', 'DiscardRequest'),
    'DiscardResult': ('src.models.contracts.github', 'DiscardResult'),
    'ConfirmDeletionsRequest': ('src.models.contracts.github', 'ConfirmDeletionsRequest'),
    'ConfirmDeletionsResult': ('src.models.contracts.github', 'ConfirmDeletionsResult'),
    'ChangedFile': ('src.models.contracts.github', 'ChangedFile'),
    'MergeConflict': ('src.models.contracts.github', 'MergeConflict'),
    'FetchResult': ('src.models.contracts.github', 'FetchResult'),
    'WorkingTreeStatus': ('src.models.contracts.github', 'WorkingTreeStatus'),
    'CommitResult': ('src.models.contracts.github', 'CommitResult'),
    'PullResult': ('src.models.contracts.github', 'PullResult'),
    'PushResult': ('src.models.contracts.github', 'PushResult'),
    'ResolveResult': ('src.models.contracts.github', 'ResolveResult'),
    'SyncResult': ('src.models.contracts.github', 'SyncResult'),
    'AbortMergeResult': ('src.models.contracts.github', 'AbortMergeResult'),
    'DiffResult': ('src.models.contracts.github', 'DiffResult'),
    'SyncExecuteRequest': ('src.models.contracts.github', 'SyncExecuteRequest'),
    'CLIFileReadRequest': ('src.models.contracts.cli', 'CLIFileReadRequest'),
    'CLIFileWriteRequest': ('src.models.contracts.cli', 'CLIFileWriteRequest'),
    'CLIFileListRequest': ('src.models.contracts.cli', 'CLIFileListRequest'),
    'CLIFileDeleteRequest': ('src.models.contracts.cli', 'CLIFileDeleteRequest'),
    'CLIConfigGetRequest': ('src.models.contracts.cli', 'CLIConfigGetRequest'),
    'CLIConfigSetRequest': ('src.models.contracts.cli', 'CLIConfigSetRequest'),
    'CLIConfigListRequest': ('src.models.contracts.cli', 'CLIConfigListRequest'),
    'CLIConfigDeleteRequest': ('src.models.contracts.cli', 'CLIConfigDeleteRequest'),
    'CLIConfigValue': ('src.models.contracts.cli', 'CLIConfigValue'),
    'CLIRegisteredWorkflow': ('src.models.contracts.cli', 'CLIRegisteredWorkflow'),
    'CLISessionRegisterRequest': ('src.models.contracts.cli', 'CLISessionRegisterRequest'),
    'CLISessionResponse': ('src.models.contracts.cli', 'CLISessionResponse'),
    'CLISessionListResponse': ('src.models.contracts.cli', 'CLISessionListResponse'),
    'CLISessionContinueRequest': ('src.models.contracts.cli', 'CLISessionContinueRequest'),
    'CLISessionContinueResponse': ('src.models.contracts.cli', 'CLISessionContinueResponse'),
    'CLISessionPendingResponse': ('src.models.contracts.cli', 'CLISessionPendingResponse'),
    'CLISessionLogRequest': ('src.models.contracts.cli', 'CLISessionLogRequest'),
    'CLISessionResultRequest': ('src.models.contracts.cli', 'CLISessionResultRequest'),
    'CLISessionExecutionSummary': ('src.models.contracts.cli', 'CLISessionExecutionSummary'),
    'ErrorResponse': ('src.models.contracts.common', 'ErrorResponse'),
    'WorkflowParameter': ('src.models.contracts.workflows', 'WorkflowParameter'),
    'WorkflowMetadata': ('src.models.contracts.workflows', 'WorkflowMetadata'),
    'DataProviderMetadata': ('src.models.contracts.workflows', 'DataProviderMetadata'),
    'MetadataResponse': ('src.models.contracts.workflows', 'MetadataResponse'),
    'FormDiscoveryMetadata': ('src.models.contracts.workflows', 'FormDiscoveryMetadata'),
    'RegisterWorkflowRequest': ('src.models.contracts.workflows', 'RegisterWorkflowRequest'),
    'RegisterWorkflowResponse': ('src.models.contracts.workflows', 'RegisterWorkflowResponse'),
    'ValidationIssue': ('src.models.contracts.workflows', 'ValidationIssue'),
    'WorkflowUpdateRequest': ('src.models.contracts.workflows', 'WorkflowUpdateRequest'),
    'WorkflowValidationRequest': ('src.models.contracts.workflows', 'WorkflowValidationRequest'),
    'WorkflowValidationResponse': ('src.models.contracts.workflows', 'WorkflowValidationResponse'),
    'EntityUsage': ('src.models.contracts.workflows', 'EntityUsage'),
    'WorkflowUsageStats': ('src.models.contracts.workflows', 'WorkflowUsageStats'),
    'WorkflowRolesResponse': ('src.models.contracts.workflows', 'WorkflowRolesResponse'),
    'AssignRolesToWorkflowRequest': ('src.models.contracts.workflows', 'AssignRolesToWorkflowRequest'),
    'DeleteWorkflowRequest': ('src.models.contracts.workflows', 'DeleteWorkflowRequest'),
    'DataProviderRequest': ('src.models.contracts.data_providers', 'DataProviderRequest'),
    'DataProviderOption': ('src.models.contracts.data_providers', 'DataProviderOption'),
    'DataProviderResponse': ('src.models.contracts.data_providers', 'DataProviderResponse'),
    'NotificationCategory': ('src.models.contracts.notifications', 'NotificationCategory'),
    'NotificationStatus': ('src.models.contracts.notifications', 'NotificationStatus'),
    'NotificationCreate': ('src.models.contracts.notifications', 'NotificationCreate'),
    'NotificationUpdate': ('src.models.contracts.notifications', 'NotificationUpdate'),
    'NotificationPublic': ('src.models.contracts.notifications', 'NotificationPublic'),
    'NotificationListResponse': ('src.models.contracts.notifications', 'NotificationListResponse'),
    'JobDispatchResponse': ('src.models.contracts.notifications', 'JobDispatchResponse'),
    'UploadLockInfo': ('src.models.contracts.notifications', 'UploadLockInfo'),
    'ProfileUpdate': ('src.models.contracts.profile', 'ProfileUpdate'),
    'PasswordChange': ('src.models.contracts.profile', 'PasswordChange'),
    'ProfileResponse': ('src.models.contracts.profile', 'ProfileResponse'),
    'MemoryDeleteResponse': ('src.models.contracts.memory', 'MemoryDeleteResponse'),
    'MemoryEntryList': ('src.models.contracts.memory', 'MemoryEntryList'),
    'MemoryEntryPublic': ('src.models.contracts.memory', 'MemoryEntryPublic'),
    'MemoryPlatformSettings': ('src.models.contracts.memory', 'MemoryPlatformSettings'),
    'MemoryPlatformSettingsUpdate': ('src.models.contracts.memory', 'MemoryPlatformSettingsUpdate'),
    'MemorySaveRequest': ('src.models.contracts.memory', 'MemorySaveRequest'),
    'MemorySearchRequest': ('src.models.contracts.memory', 'MemorySearchRequest'),
    'MemorySearchResponse': ('src.models.contracts.memory', 'MemorySearchResponse'),
    'MemorySearchResult': ('src.models.contracts.memory', 'MemorySearchResult'),
    'MemoryUserSettings': ('src.models.contracts.memory', 'MemoryUserSettings'),
    'MemoryUserSettingsUpdate': ('src.models.contracts.memory', 'MemoryUserSettingsUpdate'),
    'KubernetesStatus': ('src.models.contracts.kubernetes', 'KubernetesStatus'),
    'KubernetesExecutionJobType': ('src.models.contracts.kubernetes', 'KubernetesExecutionJobType'),
    'KubernetesExecutionSettings': ('src.models.contracts.kubernetes', 'KubernetesExecutionSettings'),
    'KubernetesExecutionUpdate': ('src.models.contracts.kubernetes', 'KubernetesExecutionUpdate'),
    'RequiredInstructionsResponse': ('src.models.contracts.required_instructions', 'RequiredInstructionsResponse'),
    'RequiredInstructionsSettings': ('src.models.contracts.required_instructions', 'RequiredInstructionsSettings'),
    'MCPServerCreate': ('src.models.contracts.external_mcp', 'MCPServerCreate'),
    'MCPServerUpdate': ('src.models.contracts.external_mcp', 'MCPServerUpdate'),
    'MCPServerSummary': ('src.models.contracts.external_mcp', 'MCPServerSummary'),
    'MCPServerPublic': ('src.models.contracts.external_mcp', 'MCPServerPublic'),
    'MCPConnectionCreate': ('src.models.contracts.external_mcp', 'MCPConnectionCreate'),
    'MCPConnectionUpdate': ('src.models.contracts.external_mcp', 'MCPConnectionUpdate'),
    'MCPConnectionSummary': ('src.models.contracts.external_mcp', 'MCPConnectionSummary'),
    'MCPConnectionPublic': ('src.models.contracts.external_mcp', 'MCPConnectionPublic'),
    'MCPConnectionToolCreate': ('src.models.contracts.external_mcp', 'MCPConnectionToolCreate'),
    'MCPConnectionToolUpdate': ('src.models.contracts.external_mcp', 'MCPConnectionToolUpdate'),
    'MCPConnectionToolPublic': ('src.models.contracts.external_mcp', 'MCPConnectionToolPublic'),
    'UserMCPCredentialCreate': ('src.models.contracts.external_mcp', 'UserMCPCredentialCreate'),
    'UserMCPCredentialPublic': ('src.models.contracts.external_mcp', 'UserMCPCredentialPublic'),
    'ConfigItemType': ('src.models.contracts.integrations', 'ConfigItemType'),
    'ConfigSchemaItem': ('src.models.contracts.integrations', 'ConfigSchemaItem'),
    'IntegrationCreate': ('src.models.contracts.integrations', 'IntegrationCreate'),
    'IntegrationUpdate': ('src.models.contracts.integrations', 'IntegrationUpdate'),
    'IntegrationResponse': ('src.models.contracts.integrations', 'IntegrationResponse'),
    'IntegrationDetailResponse': ('src.models.contracts.integrations', 'IntegrationDetailResponse'),
    'IntegrationListResponse': ('src.models.contracts.integrations', 'IntegrationListResponse'),
    'IntegrationMappingCreate': ('src.models.contracts.integrations', 'IntegrationMappingCreate'),
    'IntegrationMappingUpdate': ('src.models.contracts.integrations', 'IntegrationMappingUpdate'),
    'IntegrationMappingBatchItem': ('src.models.contracts.integrations', 'IntegrationMappingBatchItem'),
    'IntegrationMappingBatchRequest': ('src.models.contracts.integrations', 'IntegrationMappingBatchRequest'),
    'IntegrationMappingBatchResponse': ('src.models.contracts.integrations', 'IntegrationMappingBatchResponse'),
    'IntegrationMappingResponse': ('src.models.contracts.integrations', 'IntegrationMappingResponse'),
    'IntegrationMappingListResponse': ('src.models.contracts.integrations', 'IntegrationMappingListResponse'),
    'EntityIdSourceUpdateRequest': ('src.models.contracts.integrations', 'EntityIdSourceUpdateRequest'),
    'MappingAuthorizeRequest': ('src.models.contracts.integrations', 'MappingAuthorizeRequest'),
    'MappingAuthorizeResponse': ('src.models.contracts.integrations', 'MappingAuthorizeResponse'),
    'IntegrationTestRequest': ('src.models.contracts.integrations', 'IntegrationTestRequest'),
    'IntegrationTestResponse': ('src.models.contracts.integrations', 'IntegrationTestResponse'),
    'OAuthConfigSummary': ('src.models.contracts.integrations', 'OAuthConfigSummary'),
    'DecoratorType': ('src.models.contracts.decorators', 'DecoratorType'),
    'DecoratorInfo': ('src.models.contracts.decorators', 'DecoratorInfo'),
    'DecoratorPropertiesResponse': ('src.models.contracts.decorators', 'DecoratorPropertiesResponse'),
    'UpdatePropertiesRequest': ('src.models.contracts.decorators', 'UpdatePropertiesRequest'),
    'UpdatePropertiesResponse': ('src.models.contracts.decorators', 'UpdatePropertiesResponse'),
    'CleanupOrphanedResponse': ('src.models.contracts.maintenance', 'CleanupOrphanedResponse'),
    'DocsIndexResponse': ('src.models.contracts.maintenance', 'DocsIndexResponse'),
    'MaintenanceStatus': ('src.models.contracts.maintenance', 'MaintenanceStatus'),
    'OrphanedEntity': ('src.models.contracts.maintenance', 'OrphanedEntity'),
    'PreflightIssueResponse': ('src.models.contracts.maintenance', 'PreflightIssueResponse'),
    'PreflightResponse': ('src.models.contracts.maintenance', 'PreflightResponse'),
    'ReimportJobResponse': ('src.models.contracts.maintenance', 'ReimportJobResponse'),
    'ROISettingsRequest': ('src.models.contracts.roi', 'ROISettingsRequest'),
    'ROISettingsResponse': ('src.models.contracts.roi', 'ROISettingsResponse'),
    'ROISummaryResponse': ('src.models.contracts.roi', 'ROISummaryResponse'),
    'WorkflowROIEntry': ('src.models.contracts.roi', 'WorkflowROIEntry'),
    'ROIByWorkflowResponse': ('src.models.contracts.roi', 'ROIByWorkflowResponse'),
    'OrganizationROIEntry': ('src.models.contracts.roi', 'OrganizationROIEntry'),
    'ROIByOrganizationResponse': ('src.models.contracts.roi', 'ROIByOrganizationResponse'),
    'ROITrendEntry': ('src.models.contracts.roi', 'ROITrendEntry'),
    'ROITrendsResponse': ('src.models.contracts.roi', 'ROITrendsResponse'),
    'AIModelPricingBase': ('src.models.contracts.ai_usage', 'AIModelPricingBase'),
    'AIModelPricingCreate': ('src.models.contracts.ai_usage', 'AIModelPricingCreate'),
    'AIModelPricingUpdate': ('src.models.contracts.ai_usage', 'AIModelPricingUpdate'),
    'AIModelPricingPublic': ('src.models.contracts.ai_usage', 'AIModelPricingPublic'),
    'AIModelPricingListItem': ('src.models.contracts.ai_usage', 'AIModelPricingListItem'),
    'AIModelPricingListResponse': ('src.models.contracts.ai_usage', 'AIModelPricingListResponse'),
    'AIUsageBase': ('src.models.contracts.ai_usage', 'AIUsageBase'),
    'AIUsagePublic': ('src.models.contracts.ai_usage', 'AIUsagePublic'),
    'AIUsageTotals': ('src.models.contracts.ai_usage', 'AIUsageTotals'),
    'AIUsageByModel': ('src.models.contracts.ai_usage', 'AIUsageByModel'),
    'AIUsageSummaryResponse': ('src.models.contracts.ai_usage', 'AIUsageSummaryResponse'),
    'UsageReportSummary': ('src.models.contracts.ai_usage', 'UsageReportSummary'),
    'UsageTrend': ('src.models.contracts.ai_usage', 'UsageTrend'),
    'WorkflowUsage': ('src.models.contracts.ai_usage', 'WorkflowUsage'),
    'ConversationUsage': ('src.models.contracts.ai_usage', 'ConversationUsage'),
    'AgentUsage': ('src.models.contracts.ai_usage', 'AgentUsage'),
    'OrganizationUsage': ('src.models.contracts.ai_usage', 'OrganizationUsage'),
    'KnowledgeStorageUsage': ('src.models.contracts.ai_usage', 'KnowledgeStorageUsage'),
    'KnowledgeStorageTrend': ('src.models.contracts.ai_usage', 'KnowledgeStorageTrend'),
    'UsageReportResponse': ('src.models.contracts.ai_usage', 'UsageReportResponse'),
    'ConfigData': ('src.models.contracts.sdk', 'ConfigData'),
    'IntegrationData': ('src.models.contracts.sdk', 'IntegrationData'),
    'SDKOAuthCredentials': ('src.models.contracts.sdk', 'OAuthCredentials'),
    'ApplicationCreate': ('src.models.contracts.applications', 'ApplicationCreate'),
    'ApplicationUpdate': ('src.models.contracts.applications', 'ApplicationUpdate'),
    'ApplicationPublic': ('src.models.contracts.applications', 'ApplicationPublic'),
    'ApplicationListResponse': ('src.models.contracts.applications', 'ApplicationListResponse'),
    'ApplicationDefinition': ('src.models.contracts.applications', 'ApplicationDefinition'),
    'ApplicationDraftSave': ('src.models.contracts.applications', 'ApplicationDraftSave'),
    'ApplicationPublishRequest': ('src.models.contracts.applications', 'ApplicationPublishRequest'),
    'ApplicationRollbackRequest': ('src.models.contracts.applications', 'ApplicationRollbackRequest'),
    'VersionHistoryEntry': ('src.models.contracts.applications', 'VersionHistoryEntry'),
    'VersionHistoryResponse': ('src.models.contracts.applications', 'VersionHistoryResponse'),
    'AppFileCreate': ('src.models.contracts.applications', 'AppFileCreate'),
    'AppFileUpdate': ('src.models.contracts.applications', 'AppFileUpdate'),
    'AppFileResponse': ('src.models.contracts.applications', 'AppFileResponse'),
    'AppFileListResponse': ('src.models.contracts.applications', 'AppFileListResponse'),
    'PlatformJobAccepted': ('src.models.contracts.platform_jobs', 'PlatformJobAccepted'),
    'PlatformJobCancelResponse': ('src.models.contracts.platform_jobs', 'PlatformJobCancelResponse'),
    'PlatformJobError': ('src.models.contracts.platform_jobs', 'PlatformJobError'),
    'PlatformJobListResponse': ('src.models.contracts.platform_jobs', 'PlatformJobListResponse'),
    'PlatformJobProgress': ('src.models.contracts.platform_jobs', 'PlatformJobProgress'),
    'PlatformJobPublic': ('src.models.contracts.platform_jobs', 'PlatformJobPublic'),
    'PlatformJobStatus': ('src.models.contracts.platform_jobs', 'PlatformJobStatus'),
    'SchedulerCapacityStatus': ('src.models.contracts.scheduler_diagnostics', 'SchedulerCapacityStatus'),
    'SchedulerDiagnosticsResponse': ('src.models.contracts.scheduler_diagnostics', 'SchedulerDiagnosticsResponse'),
    'SchedulerLeaderStatus': ('src.models.contracts.scheduler_diagnostics', 'SchedulerLeaderStatus'),
    'SchedulerReplicaStatus': ('src.models.contracts.scheduler_diagnostics', 'SchedulerReplicaStatus'),
    'SchedulerTaskRunStatus': ('src.models.contracts.scheduler_diagnostics', 'SchedulerTaskRunStatus'),
    'SchedulerTaskStatus': ('src.models.contracts.scheduler_diagnostics', 'SchedulerTaskStatus'),
    'SystemDiagnosticLogPublic': ('src.models.contracts.scheduler_diagnostics', 'SystemDiagnosticLogPublic'),
    'PoolDetail': ('src.models.contracts.platform', 'PoolDetail'),
    'PoolsListResponse': ('src.models.contracts.platform', 'PoolsListResponse'),
    'PoolStatsResponse': ('src.models.contracts.platform', 'PoolStatsResponse'),
    'PoolSummary': ('src.models.contracts.platform', 'PoolSummary'),
    'ProcessInfo': ('src.models.contracts.platform', 'ProcessInfo'),
    'QueueItem': ('src.models.contracts.platform', 'QueueItem'),
    'QueueStatusResponse': ('src.models.contracts.platform', 'QueueStatusResponse'),
    'RecycleProcessRequest': ('src.models.contracts.platform', 'RecycleProcessRequest'),
    'RecycleProcessResponse': ('src.models.contracts.platform', 'RecycleProcessResponse'),
    'StuckHistoryResponse': ('src.models.contracts.platform', 'StuckHistoryResponse'),
    'StuckWorkflowStats': ('src.models.contracts.platform', 'StuckWorkflowStats'),
    'FilePullRequest': ('src.models.contracts.files', 'FilePullRequest'),
    'FilePullResponse': ('src.models.contracts.files', 'FilePullResponse'),
    'WatchSessionRequest': ('src.models.contracts.files', 'WatchSessionRequest'),
    'ExportMetadata': ('src.models.contracts.export_import', 'ExportMetadata'),
    'KnowledgeExportFile': ('src.models.contracts.export_import', 'KnowledgeExportFile'),
    'TableExportFile': ('src.models.contracts.export_import', 'TableExportFile'),
    'ConfigExportFile': ('src.models.contracts.export_import', 'ConfigExportFile'),
    'IntegrationExportFile': ('src.models.contracts.export_import', 'IntegrationExportFile'),
    'BulkExportRequest': ('src.models.contracts.export_import', 'BulkExportRequest'),
    'ImportResult': ('src.models.contracts.export_import', 'ImportResult'),
    'ImportResultItem': ('src.models.contracts.export_import', 'ImportResultItem'),
    'AIConnectionTestResponse': ('src.models.contracts.ai_models', 'AIConnectionTestResponse'),
    'AIModelAssignmentKey': ('src.models.contracts.ai_models', 'AIModelAssignmentKey'),
    'AIModelAssignmentResponse': ('src.models.contracts.ai_models', 'AIModelAssignmentResponse'),
    'AIModelAssignmentUpdate': ('src.models.contracts.ai_models', 'AIModelAssignmentUpdate'),
    'AIModelProfileCreate': ('src.models.contracts.ai_models', 'AIModelProfileCreate'),
    'AIModelProfileMergeRequest': ('src.models.contracts.ai_models', 'AIModelProfileMergeRequest'),
    'AIModelProfileMergeResponse': ('src.models.contracts.ai_models', 'AIModelProfileMergeResponse'),
    'AIModelProfileResponse': ('src.models.contracts.ai_models', 'AIModelProfileResponse'),
    'AIModelProfileUpdate': ('src.models.contracts.ai_models', 'AIModelProfileUpdate'),
    'AIModelsResponse': ('src.models.contracts.ai_models', 'AIModelsResponse'),
    'AIProviderConnectionCreate': ('src.models.contracts.ai_models', 'AIProviderConnectionCreate'),
    'AIProviderConnectionResponse': ('src.models.contracts.ai_models', 'AIProviderConnectionResponse'),
    'AIProviderConnectionSummary': ('src.models.contracts.ai_models', 'AIProviderConnectionSummary'),
    'AIProviderConnectionUpdate': ('src.models.contracts.ai_models', 'AIProviderConnectionUpdate'),
    'AIProviderKind': ('src.models.contracts.ai_models', 'AIProviderKind'),
}

MODEL_ALL: tuple[str, ...] = ORM_EXPORTS + ENUM_EXPORTS + CONTRACT_ALL
